----------------------------------------------------------------------------
CREATE DATABASE DTIBD
GO
----------------------------------------------------------------------------
CREATE TABLE DTI_PRODUTOS
(
	ID VARCHAR(50) NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	QUANTIDADE INT NOT NULL,
	VALORUNITARIO DECIMAL NOT NULL,

	CONSTRAINT PK_PRODUTOS PRIMARY KEY (ID),
	
	CONSTRAINT CK_PRODUTOS_NOME CHECK(NOME <> '' AND NOME IS NOT NULL),
	CONSTRAINT CK_PRODUTOS_QUANTIDADE CHECK(QUANTIDADE >= 0),
	CONSTRAINT CK_PRODUTOS_VALORUNITARIO CHECK(VALORUNITARIO >= 0)
);

ALTER TABLE DTI_PRODUTOS 
ADD CONSTRAINT DF_PRODUTOS_QUANTIDADE DEFAULT 0 FOR QUANTIDADE
GO

ALTER TABLE DTI_PRODUTOS 
ADD CONSTRAINT DF_PRODUTOS_VALORUNITARIO DEFAULT 0 FOR VALORUNITARIO
GO
----------------------------------------------------------------------------